import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import Providers from "./providers";
import CartDrawerContainer from "@/components/common/CartDrawerContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-base-100 text-base-content flex flex-col font-sans transition-colors duration-200`}
      >
        <Providers>
          <Navbar />

          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex-1 w-full">
            <main>{children}</main>
          </div>
          <CartDrawerContainer />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}